### ISSUE TITLE
Deprecate docker-compose production install?

### ISSUE THREAD

**Issue by jedie** [jedie/PyInventory#81]
I didn't use this anymore, because i use YunoHost in production: https://install-app.yunohost.org/?app=pyinventory

So i didn't test https://github.com/jedie/PyInventory/tree/master/deployment and i assume to remove this completely from this Project!

Somebody against it?

**Comment by lonesomewalker** [comment]
To be honest: yes :P
docker is now somewhat widespread, less overhead, no additional brain/hw cost.

**Comment by jedie** [comment]
Do you really use it with https://github.com/jedie/PyInventory/tree/main/deployment ???

**Comment by lonesomewalker** [comment]
I tried, but it is broken :-/

**Comment by jedie** [comment]
Hm. Okay... That's because i didn't use it anymore. So it's "untested" and not tested code is broken code ;)
That's why i open this issues. I would like to remove the [/deployment/](https://github.com/jedie/PyInventory/tree/main/deployment)  stuff completely.

I use PyInventory with YunoHost: https://yunohost.org

**Comment by lonesomewalker** [comment]
Yes, tried that yesterday.
It is A LOT of software for an easy task (running PyInventory).

So, this project becomes unmaintained for me :-/
I see no usecase for one single piece of software running a whole server stack.
DNS issues and a lot other things.
And NO, i don't like docker :-) but i have to admit that in some cases it has some advantages...

Nevertheless, thank you for your effort so far. Was looking promising!
